version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /usr/share/nginx/html
      # cause nginx is a server so file path
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
  # discard-paths: yes
